Use Faraday::Response::RaiseError middleware
### Why

To raise error when mackerel.io returns 401 Unauthorized

### How

Since `Mackerel::ApiCommand#check_status` is very simple,
change it to use built-in `Faraday::Response::RaiseError` Middleware.

### Breaking Changes

1. Change the error message to json["error"] from API.
2. All 4xx Client Error and 5xx Server Error will raise `Mackerel::Error` (`< StandardError`)

However, NoMethodError would have been raised in these following lines.

i.e. #get_services

https://github.com/mackerelio/mackerel-client-ruby/blob/v0.7.0/lib/mackerel/service.rb#L32-L33

```
data['services'].map {|s| Mackerel::Service.new(s) }
# => NoMethodError (undefined method `map' for nil:NilClass)
```

i.e. #get_host

https://github.com/mackerelio/mackerel-client-ruby/blob/v0.7.0/lib/mackerel/host.rb#L66-L67

```
Mackerel::Host.new(data['host'])
# => NoMethodError (undefined method `[]' for nil:NilClass)
```